create table
  public.classes (
    id bigint generated by default as identity not null,
    name text not null,
    selected boolean null default false,
    initials text null,
    constraint classes_pkey primary key (id),
    constraint classes_duplicate_class_key unique (name),
    constraint classes_duplicate_initials_key unique (initials)
  ) tablespace pg_default;