create table
  public.votes (
    id bigint generated by default as identity not null,
    match text not null,
    team smallint not null,
    constraint votes_pkey primary key (id)
  ) tablespace pg_default;